Update Plexus.csv
techlore/plexus pull request #272
Opened 2022-01-28 14:38 UTC by UnixPhonez

Added 10 apps (iAttended, Navy Federal Credit Union, SchoolFirst FCU, GroupMe, Canon Camera Connect, Outlook, PayRange, MyCU, SimpleLogin, Govee Home, BLEDIM

2022-02-05 15:55 UTC, Nairou requested changes

2022-02-05 15:55 UTC, Nairou commented on src/data/Plexus.csv
> +iAttended,January,2022,2,App launches with no warnings but when you go to login via email link, doesn't log you in,X,X
Comment contains a comma, needs to be quoted

2022-02-05 15:55 UTC, Nairou commented on src/data/Plexus.csv
> +PayRange,January,2022,3,Says can't work without Google services, although still lets you log in and scan for washer machines,X,X
Comment contains a comma, needs to be quoted

2022-02-06 00:08 UTC, UnixPhonez commented on src/data/Plexus.csv
> +iAttended,January,2022,2,App launches with no warnings but when you go to login via email link, doesn't log you in,X,X
fixed

2022-02-06 00:09 UTC, UnixPhonez commented on src/data/Plexus.csv
> +PayRange,January,2022,3,Says can't work without Google services, although still lets you log in and scan for washer machines,X,X
fixed

2024-09-10 04:40 UTC, henry-fisher commented
Hey there! Thank you for the patience, we've been hard at work on the Plexus app. Now that it's live, we've migrated to that system of submitting apps conveniently from your mobile device. I'll be closing this PR so that people can migrate to submitting apps directly from the mobile app. Thank you so much for your contribution and hope to see you there! 
Download the app here: https://github.com/techlore/Plexus-app?tab=readme-ov-file#download

2024-09-10 04:40 UTC, closed without merging